version: '3'
services:
  web:
    env_file:
      - .env.local
    container_name: htmx_blog_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/web
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine

    container_name: htmx_blog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '1234:5432'

    volumes:
      - db:/var/lib/postgresql/data
      - ./database/table.sql:/docker-entrypoint-initdb.d/table.sql

volumes:
  db:
    driver: local
